### ISSUE TITLE
If an error is encountered, update Postgres DB task row (`status` and `errormessage`)

### ISSUE THREAD

**Issue by rudokemper** [ConservationMetrics/mapgl-tile-renderer#50]
n/t

**Comment by IamJeffG** [comment]
This comment is just FYI and I don't think you should go divert from the existing plan.  But I read https://taylor.town/pg-task and really liked it -- it roughly describes a way that we could drop Azure Storage Queue entirely.  And in fact I've followed his pattern in something on the acoustic side, works pretty well!

**Comment by rudokemper** [comment]
Just skimmed it and it absolutely resonates with me - and I think I was hoping for something like this in the initial iteration of the design doc.

Adopting this approach will make it much easier to make the map-packer + mapgl-tile-renderer toolchain run anywhere.

But yes, this far into work towards an MVP, we probably shouldn't divert from the plan (but judging by the implementation code, I also don't think it would be a ton of work to drop ASQ for this approach, especially if you have experience on the acoustics side!)

**Comment by IamJeffG** [comment]
One reason I suggest holding off is it will require refactoring / splitting your SQL tables.  This wasn't obvious to me at first but I quickly found out when implementing.  Basically the task queue table needs to be only a task queue, and cannot power anything else, e.g. the list of maps in the webapp.
